name: "Terraform"

on:
  workflow_dispatch:
  pull_request:

env:
  GITHUB_OWNER: ${{ inputs.github_org }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  TF_WORKSPACE: happypathway
  
jobs:
  terraform-validate:
    uses: HappyPathway/centralized-actions/.github/workflows/terraform-test.yml@main
    with:
      terraform_version: ${{ vars.terraform_version }}
      terraform_api: ${{ vars.terraform_api }}
      github_username: ${{ github.actor }}
      github_email: ${{ github.actor }}@roknsound.com
      github_org: ${{ github.repository_owner }}
    secrets:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
     
  terraform-plan:
    needs: terraform-validate
    uses: HappyPathway/centralized-actions/.github/workflows/terraform-plan.yaml@main
    with:
      terraform_version: ${{ vars.terraform_version }}
      terraform_api: ${{ vars.terraform_api }}
      github_username: ${{ github.actor }}
      github_email: ${{ github.actor }}@roknsound.com
      github_org: ${{ github.repository_owner }} 
      workspace: happypathway
    secrets:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    
  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: requires_approval
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Terraform Init
        run: terraform init

      - uses: actions/download-artifact@master
        with:
          name: ${{ needs.terraform-plan.outputs.planfile }}
          path: tf_plan
          
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tf_plan/${{ needs.terraform-plan.outputs.planfile }}
