name: "Terraform"

on:
  workflow_dispatch:
  pull_request:

env:
  GITHUB_OWNER: ${{ inputs.github_org }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  TF_WORKSPACE: happypathway
  
jobs:
  setup-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ vars.terraform_version }}
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
          cli_config_credentials_hostname: ${{ vars.terraform_api }}
          
      - name: terraform init
        run: terraform init -upgrade

      - uses: actions/upload-artifact@master
        name: Archive Configuration
        if: github.ref == 'refs/heads/main'
        with:
          name: terraform_dir
          path: .terraform
          retention-days: 1
          include-hidden-files: true
          
          
  terraform-validate:
    needs: setup-terraform
    uses: HappyPathway/centralized-actions/.github/workflows/terraform-test.yml@main
    with:
      terraform_version: ${{ vars.terraform_version }}
      terraform_api: ${{ vars.terraform_api }}
      github_username: ${{ github.actor }}
      github_email: ${{ github.actor }}@roknsound.com
      github_org: ${{ github.repository_owner }}
      setup_terraform: false
      terraform_init: false
      cache: ${{ github.workspace }}
      download_cache: true
    secrets:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
     
  terraform-plan:
    needs: terraform-validate
    uses: HappyPathway/centralized-actions/.github/workflows/terraform-plan.yaml@main
    with:
      terraform_version: ${{ vars.terraform_version }}
      terraform_api: ${{ vars.terraform_api }}
      github_username: ${{ github.actor }}
      github_email: ${{ github.actor }}@roknsound.com
      github_org: ${{ github.repository_owner }} 
      workspace: happypathway
      setup_terraform: false
      terraform_init: true
      cache: ${{ github.workspace }}
      download_cache: true
    secrets:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    
  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: requires_approval
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: terraform_dir
          path: ${{ github.workspace }}/.terraform

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.terraform-plan.outputs.commit_sha }}
          persist-credentials: false
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
